config/routes.rb
Rails.application.routes.draw do

  resources :home, only: :index do
    collection do
      get :upload, action: 'upload_form'
      post :upload, action: 'upload_process'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
    has_and_belongs_to_many :people, join_table: "affiliations_people"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
    has_and_belongs_to_many :people, join_table: "locations_people"
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  has_and_belongs_to_many :locations, join_table: 'locations_people'
  has_and_belongs_to_many :affiliations, join_table: 'affiliations_people'

  validates :name, :species, :gender, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'csv'
require 'import_csv/data'

class HomeController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    all_users = Person.all.includes(:locations, :affiliations)
    all_users = all_users.where('name LIKE ?', params[:search]) if params[:search]
    @users = all_users.paginate(page: params[:page], per_page: 10).order(sort_column+ ' ' + sort_direction)
  end

  def upload_form
  end

  def upload_process
    file = params[:home][:file]
    data = CSV.parse(file.to_io, headers: true, encoding: 'utf8')

    ImportCsv::Data.new(data).import

    redirect_to root_path
  end

  private

  def sort_column
    Person.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}, {:class => css_class}
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_search.html.erb
<%= form_tag root_path, :method => 'get', :id => "db_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/home/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.locations.pluck(:name).join(',') %></td>
  <td><%= user.species %></td>
  <td><%= user.gender %></td>
  <td><%= user.affiliations.pluck(:name).join(',') %></td>
  <td><%= user.weapon %></td>
  <td><%= user.vehicle %></td>
</tr>

app/views/home/index.html.erb
<h1>Users</h1>
<p><%= @users.count %> user(s) in the database.</p>

<%= render partial: 'search' %>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= sortable 'name' %></th>
      <th scope="col">Locations</th>
      <th scope="col"><%= sortable 'species' %></th>
      <th scope="col"><%= sortable 'gender' %></th>
      <th scope="col">Affilications</th>
      <th scope="col"><%= sortable 'weapon' %>Weapon</th>
      <th scope="col"><%= sortable 'vehicle' %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'user', collection: @users %>
  </tbody>
</table>

<%= will_paginate @users %>

app/views/home/upload_form.html.erb
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    Import products from CSV
  </h1>
</header>

<section class="main-content__body main-content__body">
  <%= form_for :home, html: { class: "form" } do |f| %>
    <p><%= f.file_field(:file) %></p>
    <p><%= f.submit "Upload" %></p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='container'>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <%= link_to 'Dashboard', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item float-right">
              <%= link_to "Upload CSV file", upload_home_index_path %>
            </li>
        </div>
      </nav>
    </div>

    <main role="main" class="container">
      <div class='mt-5 pt-5'>
        <%= yield %>
      </div>
    </main>
  </body>
</html>